on: [push]

jobs:
  push_docs:
    runs-on: ubuntu-latest
    name: Test the action locally
    env:
      # Github.refname is wrong for pull requests - have to use head ref for them
      MYREF: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Push Docs (test building docs, with dir and subdir and versioning)
        uses: "./" # Uses an action in the root directory
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ vars.AWS_REGION }}
          aws_s3_bucket: ${{ vars.AWS_S3_BUCKET_DOCS }}
          aws_cloudfront_distribution_id: ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID_DOCS }}
          mkdocs_file: "mkdocs.yml"
          version_string: "${{ env.MYREF }}"
          bucket_subdir: "testdocs"
          bucket_dir: "docs.powerdns.com"
      - name: Push Docs (test building docs and and subdir but no versioning)
        uses: "./" # Uses an action in the root directory
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ vars.AWS_REGION }}
          aws_s3_bucket: ${{ vars.AWS_S3_BUCKET_DOCS }}
          aws_cloudfront_distribution_id: ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID_DOCS }}
          mkdocs_file: "mkdocs.yml"
          bucket_subdir: "testdocs-noversion"
          version_control: "false"
      - name: Push Docs (test building docs no versioning and no subdir)
        uses: "./" # Uses an action in the root directory
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ vars.AWS_REGION }}
          aws_s3_bucket: ${{ vars.AWS_S3_BUCKET_DOCS }}
          aws_cloudfront_distribution_id: ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID_DNSDIST }}
          build_docs: "false"
          version_control: "false"
          bucket_dir: "dnsdist.org"
          docs_dir: "prebuilt_docs"
